### ISSUE TITLE
作者是否考虑集成 Markdown Math?

### ISSUE THREAD

**Issue by Sec-ant** [CoolSpring8/yacu#1]
之前自己写的一个脚本，也是劫持了 fetch，有兴趣的话可以放到你这个脚本里面：https://greasyfork.org/zh-CN/scripts/426133-cc98-markdown-math

**Comment by CoolSpring8** [comment]
感谢，我建了一个分支把代码拷贝进来（#2），功能上应该正常，请看一下这样的 attribution 可以吗？另外这个仓库的开源许可证还没放置，可能会是 MIT

**Comment by Sec-ant** [comment]
我这边没问题~

**Comment by CoolSpring8** [comment]
好的，再次感谢~

ps：改名时改了 `@name` 和 `@namespace`，所以从 GreasyFork 获得的版本需要重新安装
